const EvtType = {
  ENTER: "ENTER",
  // cards to client
  TEXT: "TEXT",
  TRICK: "TRICK",
  DEAL: "DEAL",
  TRUMP: "TRUMP",
  CARD: "CARD",
  SELECT_YESNO: "SELECT_YESNO",
  SELECT_BID: "SELECT_BID",
  SELECT_CARD: "SELECT_CARD",
  SELECT_SUIT: "SELECT_SUIT",
  // cards to server
  SELECT_YESNO_RESPONSE: "SELECT_YESNO_RESPONSE",
  SELECT_BID_RESPONSE: "SELECT_BID_RESPONSE",
  SELECT_CARD_RESPONSE: "SELECT_CARD_RESPONSE",
  SELECT_SUIT_RESPONSE: "SELECT_SUIT_RESPONSE",

  // field to client
  FIELD_PLACE: "FIELD_PLACE",
  FIELD_REMOVE: "FIELD_REMOVE",
  SELECT_FIELD_MOVE: "SELECT_FIELD_MOVE",
  SELECT_PROMOTION: "SELECT_PROMOTION",
  // field to server
  SELECT_FIELD_MOVE_RESPONSE: "SELECT_FIELD_MOVE_RESPONSE",
  SELECT_PROMOTION_RESPONSE: "SELECT_PROMOTION_RESPONSE"
}

